### ISSUE TITLE
RJ45 addon-board for PATCH

### ISSUE THREAD

**Issue by CoogLFish** [m0xpd/PATCH#1]
Hello Paul,
this obviously isn't an issue but a suggestion. Wouldn't it be a nice idea to include a RJ45-board into your collection to _internally_ connect two cases via an ethernet cable? I know there are several solutions commercially available (including Doepfer) to accomplish this _externally_, but not inside the cases.

**Comment by m0xpd** [comment]
Thanks for raising this interesting idea, which falls nicely within the scope of 'Patch'. I certainly hadn't thought of it. 

I've heard of the Doepfer (etc) solutions, but I don't know anything about them. To be honest, I first assumed they were active devices, which made a local network connection over the cable and encoded the data for transmission. But on reflection, I guess that either a buffered connection or even a simple passive connection over the twisted pairs of a 'CatX' cable would work. 

Thanks again for raising this.

**Comment by awonak** [comment]
I have been working on a few passive patch bay via Ethernet modules if you'd like to check them out for any inspiration: https://github.com/awonak/ether-twin
